In [ ]:
from psutil import virtual_memory
ram_gb = virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))

if ram_gb < 20:
  print('To enable a high-RAM runtime, select the Runtime > "Change runtime type"')
  print('menu, and then select High-RAM in the Runtime shape dropdown. Then, ')
  print('re-execute this cell.')
else:
  print('You are using a high-RAM runtime!')

Your runtime has 27.4 gigabytes of available RAM

You are using a high-RAM runtime!


In [ ]:
pip install pandas-profiling

In [ ]:
!pip install tweepy
!pip install wordcloud
!pip install textblob

In [ ]:
import pandas_profiling
import tweepy                   
from google.colab import drive  
import json
import csv
from datetime import date
from datetime import datetime
import time
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sb
import re
import time
import string
import warnings

# for all NLP related operations on text
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import *
from wordcloud import WordCloud
import matplotlib.animation as animation
import operator
import plotly.express as px
from collections import Counter

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, confusion_matrix
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB


# To consume Twitter's API
import tweepy
from tweepy import OAuthHandler 

# To identify the sentiment of text
from textblob import TextBlob

# ignoring all the warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

# downloading stopwords corpus
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('vader_lexicon')
nltk.download('averaged_perceptron_tagger')
nltk.download('punkt')
stopwords = set(stopwords.words("english"))

/usr/local/lib/python3.6/dist-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
drive.mount('/content/gdrive')
path = './gdrive/MyDrive/WDPS_data'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
df = pd.read_csv("/content/gdrive/MyDrive/WDPS_Data/cleanedElectiontweetsFinal")

In [ ]:
df.head()

renderedContent  ...                                           Count(#)
0  Billet #1 ~ #USElections2020 \nMaintenant que ...  ...                         # #USElections # #JoeBiden
1  #USElections2020 #JoeBiden pas encore élu, mai...  ...                             #USElections #JoeBiden
2  #barrons #cnbc #bloomberg #stocks #money #spor...  ...  #barrons #cnbc #bloomberg #stocks #money #spor...
3  “Finally, don’t bothsides this. The decay of U...  ...                                       #USElections
4  #USElections2020 #JoeBiden nous concocte un pr...  ...                   #USElections #JoeBiden #JoeBiden

[5 rows x 5 columns]

In [ ]:
df = df.drop(['renderedContent'], axis = 1)
df = df.drop(['id'], axis = 1)
df = df.drop(['Count(#)'], axis = 1)

In [ ]:
df.shape

(79832, 2)

In [ ]:
dff = df.drop(['sentiment'], axis = 1)

In [ ]:
dff.shape

(79832, 1)

In [ ]:
from sklearn.model_selection import train_test_split
x_temp, x_test, y_temp, y_test = train_test_split(dff, list(df.sentiment), test_size=0.1)

In [ ]:
x_test.shape

(7984, 1)

In [ ]:
x_temp.shape

(71848, 1)

In [ ]:
len(y_test)

7984

In [ ]:
type(y_temp)

list

In [ ]:
x_temp['sentiment'] = y_temp

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [ ]:
x_temp.head()

refinedTweets sentiment
50268                   #uselect twittercombarackobamast  positive
10964                       aous sendoff #trump #uselect  positive
70346  Im constitut lawyer sure #uselect wake call am...  positive
32228         ultim biden lead wisconsin #elect #uselect  positive
73084  noth better #dogsoftwitt pawfect thing focu we...  positive

In [ ]:
type(x_temp)

pandas.core.frame.DataFrame

In [ ]:
positive = x_temp[x_temp['sentiment'] == 'positive']

In [ ]:
positive.head()

refinedTweets sentiment
50268                   #uselect twittercombarackobamast  positive
10964                       aous sendoff #trump #uselect  positive
70346  Im constitut lawyer sure #uselect wake call am...  positive
32228         ultim biden lead wisconsin #elect #uselect  positive
73084  noth better #dogsoftwitt pawfect thing focu we...  positive

In [ ]:
negative = x_temp[x_temp['sentiment'] == 'negative']

In [ ]:
negative.head()

refinedTweets sentiment
79074  the second wave corona came case increas count...  negative
55166  oughli two decad ago I vote serbia milosev reg...  negative
33750  aepublican candid run state legislatur state n...  negative
59695  jackthorn ye leav yule time season two #hisdar...  negative
10693  #now look like giant donald trump blow rat arr...  negative

In [ ]:
negative.shape[0]

7809

In [ ]:
positivesample = positive.sample(n = negative.shape[0])

In [ ]:
positivesample.head()

refinedTweets sentiment
59268  thi may quot #uselect appli right makevotesmat...  positive
56788  cnnpolit #view #viewview #subscrib #subsub #yo...  positive
9425   #congress presid #soniagandhi extend warmest c...  positive
17514  heeeeeel langzaaaaaam gaaaaat georgiaaaa richt...  positive
58517                                   here go #uselect  positive

In [ ]:
positivesample.shape

(7809, 2)

In [ ]:
ds = pd.concat([negative, positivesample], axis = 0)

In [ ]:
ds.tail()

refinedTweets sentiment
22511  #uselect phoenix becom tech centr mani univers...  positive
66366  our final elect predict #elect #vote #vote #vo...  positive
32077  could realdonaldtrump sens defeat talk sit pre...  positive
54718  To american friend today stress day normal you...  positive
11845  acist trump out well done usa #elect #uselect ...  positive

In [ ]:
ds.shape

(15618, 2)

In [ ]:
ds.to_csv("/content/gdrive/MyDrive/WDPS_Data/trainset.csv")

In [ ]:
ds.head()

refinedTweets sentiment
79074  the second wave corona came case increas count...  negative
55166  oughli two decad ago I vote serbia milosev reg...  negative
33750  aepublican candid run state legislatur state n...  negative
59695  jackthorn ye leav yule time season two #hisdar...  negative
10693  #now look like giant donald trump blow rat arr...  negative

In [ ]:
ds_temp = ds

In [ ]:
test_df = x_test
test_df['sentiment'] = y_test

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [ ]:
ds_temp.shape

(15618, 2)

In [ ]:
test_df.shape

(7984, 2)

In [ ]:
ds = pd.concat([ds_temp, test_df], axis = 0)

In [ ]:
ds.head()

refinedTweets sentiment
79074  the second wave corona came case increas count...  negative
55166  oughli two decad ago I vote serbia milosev reg...  negative
33750  aepublican candid run state legislatur state n...  negative
59695  jackthorn ye leav yule time season two #hisdar...  negative
10693  #now look like giant donald trump blow rat arr...  negative

In [ ]:
ds.shape

(23602, 2)

In [ ]:
test_df.head()

refinedTweets sentiment
47625  I not wait night follow what go #uselect count...  negative
4188   thank jkcorden woooow aaaaalll netwooork stuck...  positive
62523  If stomach terrifi essenti listen possibl outc...  negative
54031  today mani u feel anxieti fear anger sad hella...  positive
19356              the spirit strong flesh weak #uselect  positive

In [ ]:
list(test_df.index)

[47625,
 4188,
 62523,
 54031,
 19356,
 38516,
 78669,
 79458,
 56343,
 14438,
 35026,
 6097,
 6810,
 70995,
 59792,
 61695,
 62340,
 39894,
 74001,
 57545,
 54512,
 50903,
 76174,
 33829,
 49502,
 22726,
 25035,
 76892,
 3015,
 10616,
 56741,
 6762,
 22328,
 63680,
 18877,
 27315,
 7482,
 32053,
 3597,
 9452,
 70506,
 63835,
 63032,
 13898,
 44639,
 30560,
 24036,
 78933,
 51302,
 79272,
 19923,
 59762,
 9827,
 64747,
 42147,
 52203,
 3653,
 29121,
 34629,
 38768,
 27157,
 31290,
 32610,
 20493,
 279,
 20903,
 46666,
 39742,
 43624,
 19739,
 9789,
 13588,
 48206,
 40027,
 45772,
 6797,
 24073,
 219,
 20891,
 67233,
 39637,
 42942,
 14406,
 66390,
 17756,
 25861,
 75020,
 52417,
 8704,
 22011,
 66463,
 23639,
 35834,
 53336,
 62563,
 48488,
 33365,
 36712,
 6995,
 65666,
 36732,
 46584,
 9094,
 58022,
 44894,
 55374,
 67777,
 25670,
 7391,
 26309,
 45,
 32087,
 31611,
 20622,
 11156,
 37973,
 31252,
 75364,
 14698,
 9986,
 66255,
 69594,
 64460,
 7363,
 45767,
 78736,
 4203,
 35543,
 4

In [ ]:
corpus = []
for i in range(ds.shape[0]):
    corpus.append(ds.iloc[i][0])

In [ ]:
len(corpus)

23602

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf_vectors = TfidfVectorizer(max_df=0.90, min_df=2, max_features=9000, 
                                stop_words='english',
                                ngram_range=(1, 3))

In [ ]:
tfidf_only_fit = tfidf_vectors.fit(corpus)

In [ ]:
tfidf = tfidf_vectors.fit_transform(corpus)

In [ ]:
df_vector = pd.DataFrame(tfidf.todense(),columns = tfidf_vectors.get_feature_names())

In [ ]:
df_vector

aa  aa rhe  aab  aab ki  ...  zum  zur  zur uswahl  zwischenstand
0      0.0     0.0  0.0     0.0  ...  0.0  0.0         0.0            0.0
1      0.0     0.0  0.0     0.0  ...  0.0  0.0         0.0            0.0
2      0.0     0.0  0.0     0.0  ...  0.0  0.0         0.0            0.0
3      0.0     0.0  0.0     0.0  ...  0.0  0.0         0.0            0.0
4      0.0     0.0  0.0     0.0  ...  0.0  0.0         0.0            0.0
...    ...     ...  ...     ...  ...  ...  ...         ...            ...
23597  0.0     0.0  0.0     0.0  ...  0.0  0.0         0.0            0.0
23598  0.0     0.0  0.0     0.0  ...  0.0  0.0         0.0            0.0
23599  0.0     0.0  0.0     0.0  ...  0.0  0.0         0.0            0.0
23600  0.0     0.0  0.0     0.0  ...  0.0  0.0         0.0            0.0
23601  0.0     0.0  0.0     0.0  ...  0.0  0.0         0.0            0.0

[23602 rows x 9000 columns]

In [ ]:
tdf = df_vector
tdf['labelxyz'] = list(ds.sentiment)

In [ ]:
tdf.tail()

aa  aa rhe  aab  aab ki  ...  zur  zur uswahl  zwischenstand  labelxyz
23597  0.0     0.0  0.0     0.0  ...  0.0         0.0            0.0  positive
23598  0.0     0.0  0.0     0.0  ...  0.0         0.0            0.0  positive
23599  0.0     0.0  0.0     0.0  ...  0.0         0.0            0.0  positive
23600  0.0     0.0  0.0     0.0  ...  0.0         0.0            0.0  negative
23601  0.0     0.0  0.0     0.0  ...  0.0         0.0            0.0  negative

[5 rows x 9001 columns]

In [ ]:
tdf_negative = tdf[tdf.labelxyz == 'negative']

In [ ]:
tdf_negative.shape

(8679, 9001)

In [ ]:
tdf_positive = tdf[tdf.labelxyz == 'positive']

In [ ]:
tdf_positive.shape

(14923, 9001)

In [ ]:
x_train_negative = tdf_negative.sample(frac=0.9, random_state=0)

In [ ]:
x_test_negative = tdf_negative.drop(x_train_negative.index)

In [ ]:
x_train_positive =  tdf_positive.sample(frac=0.406, random_state=0)

In [ ]:
x_test_positive = tdf_positive.drop(x_train_positive.index)

In [ ]:
x_train_df = pd.concat([x_train_negative, x_train_positive], axis = 0)

In [ ]:
x_train = x_train_df.drop(['labelxyz'], axis = 1)

In [ ]:
y_train = list(x_train_df.labelxyz)

In [ ]:
x_test_df = pd.concat([x_test_negative, x_test_positive], axis = 0)

In [ ]:
x_test = x_test_df.drop(['labelxyz'], axis = 1)

In [ ]:
y_test = list(x_test_df.labelxyz)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

In [ ]:
from sklearn.model_selection import cross_val_score

LR = LogisticRegression()
LR_scores = cross_val_score(LR, x_train, y_train, cv=3)
LR_mean = LR_scores.mean()

NB = GaussianNB()
NB_scores = cross_val_score(NB, x_train, y_train, cv=3)
NB_mean = NB_scores.mean()

d = {'Classifiers': ['Logistic Reg.', 'Naives Bayes'], 
    'Crossval Mean Scores': [LR_mean, NB_mean]}
    
result_df = pd.DataFrame(data=d)

In [ ]:
result_df

Classifiers  Crossval Mean Scores
0  Logistic Reg.              0.806850
1   Naives Bayes              0.685796

In [ ]:
from sklearn.metrics import accuracy_score
NB = GaussianNB()
NB.fit(x_train, y_train)
predict_NB = NB.predict(x_test)
accuracy_score(y_test, predict_NB)

0.4332100287710645

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predict_NB)

array([[ 811,   57],
       [5459, 3405]])

In [ ]:
predictedLabelsNB = predict_NB[np.newaxis].T
predictedLabelsNB 

array([['negative'],
       ['negative'],
       ['negative'],
       ...,
       ['positive'],
       ['positive'],
       ['positive']], dtype='<U8')

In [ ]:
LR = LogisticRegression()
LR.fit(x_train, y_train)
predict_LR = LR.predict(x_test)
accuracy_score(y_test, predict_LR)

0.7763049732840115

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predict_LR)

array([[ 782,   86],
       [2091, 6773]])

In [ ]:
predictedLabelsLog = predict_LR[np.newaxis].T
predictedLabelsLog 

array([['negative'],
       ['negative'],
       ['negative'],
       ...,
       ['positive'],
       ['positive'],
       ['positive']], dtype='<U8')

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
RF = RandomForestClassifier()
RF.fit(x_train, y_train)
predict_RF = RF.predict(x_test)
accuracy_score(y_test, predict_RF)

0.750924784217016

In [ ]:
confusion_matrix(y_test, predict_RF)

array([[ 775,   93],
       [2331, 6533]])

In [ ]:
predictedLabelsRF = predict_RF[np.newaxis].T
predictedLabelsRF 

array([['negative'],
       ['negative'],
       ['positive'],
       ...,
       ['positive'],
       ['positive'],
       ['positive']], dtype='<U8')

In [ ]:
from sklearn import tree
DT = tree.DecisionTreeClassifier()
DT.fit(x_train, y_train)
predict_DT = DT.predict(x_test)
accuracy_score(y_test, predict_DT)

0.7427044800657624

In [ ]:
confusion_matrix(y_test, predict_DT)

array([[ 698,  170],
       [2334, 6530]])

In [ ]:
predictedLabelsDT = predict_DT[np.newaxis].T
predictedLabelsDT 

array([['negative'],
       ['positive'],
       ['negative'],
       ...,
       ['positive'],
       ['positive'],
       ['positive']], dtype='<U8')

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
GB = GradientBoostingClassifier()
GB.fit(x_train, y_train)
predict_GB = GB.predict(x_test)
accuracy_score(y_test, predict_GB)

0.3840937114673243

In [ ]:
confusion_matrix(y_test, predict_GB)

array([[ 833,   35],
       [5959, 2905]])

In [ ]:
predictedLabelsGB = predict_GB[np.newaxis].T
predictedLabelsGB 

array([['negative'],
       ['positive'],
       ['negative'],
       ...,
       ['positive'],
       ['negative'],
       ['positive']], dtype='<U8')